- name: Déploiement Docker
  hosts: apps
  vars_files:
    - group_vars/apps.yml
 
  tasks:
    - name: Créer le dossier pour l'application
      file:
        path: "{{ app_directory }}"
        state: directory

    - name: Se connecter au registre Docker privé
      docker_login:
        registry: "{{ registry }}"
        username: "{{ registry_login }}"
        password: "{{ registry_password }}"

    - name: Copier le fichier docker-compose.yml dans le répertoire de l'application
      copy:
        src: "docker-compose.yml.j2"
        dest: "{{ app_directory }}/docker-compose.yml"
      vars:
        env: "{{ env }}"

    - name: Copier le fichier backend.env dans le répertoire de l'application
      copy:
        src: "backend.env.j2"
        dest: "{{ app_directory }}/backend.env"
      vars:
        env: "{{ env }}"

    - name: Puller les images Docker avec docker-compose
      command:
        cmd: "docker compose pull"
        chdir: "{{ app_directory }}"

    - name: Démarrer les containers Docker
      command:
        cmd: "docker compose up -d --remove-orphans"
        chdir: "{{ app_directory }}"
