services:
  julian-marques-frontend:
    container_name: julian-marques-frontend
    image: docker.iut.arcanit.io/julian-marques-frontend:latest
    restart: always
    networks: [ traefik ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-julian-marques-frontend.rule=Host(`dev-julian-marques.iut.arcanit.io`)"
      - "traefik.http.routers.dev-julian-marques-frontend.entrypoints=https"
      - "traefik.http.routers.dev-julian-marques-frontend.tls=true"
      - "traefik.http.services.dev-julian-marques-frontend.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
