name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: docker.iut.arcanit.io
          username: ${{ secrets.NOM }}
          password: ${{ secrets.PWD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/web.dockerfile
          push: true
          tags: |
            ${{ secrets.ADRESSE }}/frontend:latest
            ${{ secrets.ADRESSE }}/frontend:${{ github.sha }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: docker.iut.arcanit.io
          username: ${{ secrets.NOM }}
          password: ${{ secrets.PWD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/api.dockerfile
          push: true
          tags: |
            ${{ secrets.ADRESSE }}/backend:latest
            ${{ secrets.ADRESSE }}/backend:${{ github.sha }}
  
  deploy-dev:
    name: Deploy to dev server
    runs-on: ubuntu-latest
    needs: ["build-frontend", "build-backend"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 62215 dev15.iut.arcanit.io >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH }}

      - name: Install Ansible
        run: |
        
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          cd ansible/ 
          ansible-playbook deploy.yml \
            -i inventory.ini \
            -e "image_tag=${{ github.sha }}" \
            -e "registry_password=${{ secrets.PWD }}"