name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      inventory:
        required: true
        type: string
    secrets:
      SSH:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_ADRESSE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 62218 dev18.iut.arcanit.io >> ~/.ssh/known_hosts

      - name: Installer Ansible et la collection Docker
        run: |
          pip3 install ansible
          ansible-galaxy collection install community.docker

      - name: Lancer le playbook
        run: |
          cd ansible/
          ansible-playbook -i ${{ inputs.inventory }} deploy.yml \
            --extra-vars "env=${{ inputs.environment }} image_tag=${{ github.sha }} registry_password=${{ secrets.DOCKER_PASSWORD }}"